# Fly.io Backend Deployment

# Fly.io app configuration
app = "reporting-api-testing"
primary_region = "sin" # Singapore - change to your nearest region

[build]

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[vm]]
  cpu_kind = "shared"
  cpus = 4
  memory_mb = 1024
